[package]
name = "midi"
version = "0.1.0"
edition = "2024"

[dependencies]
embassy-sync = "0.7.2"
midly = { version = "0.5.3", default-features = false }

[dev-dependencies]
midly = { version = "0.5.3" }
pretty_assertions = "1.4.1"
